### ISSUE TITLE
copyWith handles nulls incorrectly

### ISSUE THREAD

**Issue by ildarsharafutdinov** [spkersten/dart_functional_data#11]
hi,

```
final copyWith = '$className copyWith({${fields.map((f) => '${f.type} ${f.name}').join(', ')}}) => $className(${fields.map((f) => '${f.name}: ${f.name} ?? this.${f.name}').join(', ')});';
```

Generated code doesn't update nullable properties. E.g. `x.copyWith(myProp: null)` ignores myProp.

**Comment by spkersten** [comment]
This is a feature, but a bug 🙂. All `copyWith`’s parameters are optional,
which means they are null then not specified when the method is called. So
essentially, null is used to indicate not to change the value of that
corresponding field.

If you want to allow the absence of a value, you could use the `Optional`
class that this package provides. That has as added advantage that you get
more type safety and the interface of the class becomes more clear (it is
obvious what is optional and what isn’t). Slightly increased verbosity is a
down side of this approach of course.
