### ISSUE TITLE
`Optional<T>` does not override equality test

### ISSUE THREAD

**Issue by werediver** [spkersten/dart_functional_data#14]
As of now the embedded [Optional\<T\>](https://github.com/spkersten/dart_functional_data/blob/b47022927bd1cbae6c2c3287fac8480c61f000ae/functional_data/lib/src/lenses.dart#L134) does not override the equality test `==`, which complicates testing equality of structures with optionals (not only classes with optional members, but also collections with optional items).

Discovered by @alexei-sintotski, opening a ticket for the sake of documenting the issue.

**Comment by spkersten** [comment]
Now Optional from plain_optional is used.
