### ISSUE TITLE
Allow Analyzer version >= 0.39.0

### ISSUE THREAD

**Issue by TadasValaitiz** [spkersten/dart_functional_data#19]
Currently `functional_data_generator` have version constraints:
`analyzer: ">=0.38.1 <0.39.0"`

This creates issues with `pub get` and other dependencies

**Comment by Tadas44** [comment]
This issue is blocking to upgrade Flutter to higher versions because most packages rely on `analyzer:>0.39` . This is example of `test` package:

  ```Because no versions of functional_data_generator match >0.3.3 <0.4.0 and functional_data_generator 0.3.3 depends on analyzer ^0.38.1, functional_data_generator ^0.3.3 requires analyzer ^0.38.1.```

```(1) So, because test_core >=0.3.8 <0.3.12-nullsafety depends on analyzer ^0.39.5, functional_data_generator ^0.3.3 is incompatible with test_core >=0.3.8 <0.3.12-nullsafety.```

@spkersten @remonh87 @miguelcmedeiros can you please  look into it?

**Comment by spkersten** [comment]
I'll try to release a new version today

**Comment by Tadas44** [comment]
Thanks :)

**Comment by spkersten** [comment]
Should work with 0.3.4 of functional_data_generator.

**Comment by kika** [comment]
@spkersten where do you publish now? The latest on pub.dev is 0.3.0

**Comment by spkersten** [comment]
You must be confusing the generator package with the annotations package

**Comment by kika** [comment]
@spkersten my fault, I assumed they are on the same timeline. BTW, it's broken again with the latest Flutter stable (1.22) which is Dart 2.10 and requires analyzer 0.40

**Comment by spkersten** [comment]
@kika I've published a new version allowing the latest versions of analyzer
