### ISSUE TITLE
Problem with static const fields

### ISSUE THREAD

**Issue by ValeriusGC** [spkersten/dart_functional_data#4]
When i try do something like
  static const _minCnt = 1;
  static const _maxCnt = 6;
```dart
class Model extends $Model {
  static const _minCnt = 1;
  static const _maxCnt = 6;
...
```
i got errorous implementation :
```dart
abstract class $Model {
  int get _minCnt;
  int get _maxCnt;
  const $Model();
  Model copyWith(
          {int _minCnt,
          int _maxCnt,

```

**Comment by spkersten** [comment]
Thanks for reporting this. Looks like static fields aren't filtered out yet.

**Comment by spkersten** [comment]
I've fixed the issue. New version will be published shortly.
