### ISSUE TITLE
Class can't be used as mixin because it declares constructor...

### ISSUE THREAD

**Issue by ValeriusGC** [spkersten/dart_functional_data#5]
in your sample:
```
@FunctionalData()
class Foo with $Foo {
  final int number;
  final String name;

  // Can't be const because of mixin
  Foo({this.number, this.name});
}
```
in real life i got error **Class can't be used as mixin because it declares constructor...**
```dart
@immutable
@FunctionalData()
class Base with $Base{
  final int uid;
  final int editTime;

  Base({this.uid, this.editTime});
}
```

**Comment by ValeriusGC** [comment]
So, how one can use this with inheritance?

**Comment by spkersten** [comment]
Looks like a mistake in the documentation (or a left-over from an earlier incarnation). Instead: `class Base extends $Base` should work.

**Comment by spkersten** [comment]
I've fixed the documentation.

**Comment by ValeriusGC** [comment]
So, is it planning to use this with inheritance?

**Comment by jaggerwang** [comment]
@spkersten Can the generated class to be a mixin? As dart not support multiple inheritance.
