### ISSUE TITLE
Collections are incorrect in equals.

### ISSUE THREAD

**Issue by ValeriusGC** [spkersten/dart_functional_data#6]
```=()``` generates incorrect code for collection so 
```
@FunctionalData()
class MyList extends $MyList{
  final List<int> items;

  MyList({this.items});
}


  test('list test', (){

    final list1 = MyList(items: [1,2,3]);
    final list2 = MyList(items: [1,2,3]);
    expect(list2, equals(list1));

  });

```
makes error.

It's all because of incorrect collection equality, see https://stackoverflow.com/questions/10404516/how-can-i-compare-lists-for-equality-in-dart

**Comment by spkersten** [comment]
You can annotate fields if you don’t want the types equality operator but a
custom one. For example:
```
@CustomEquality(DeepCollectionEquality())
final List<int> number;
```

**Comment by ValeriusGC** [comment]
... and don’t forget to remake the `*g.dart` file. Otherwise it doesn’t work. Thanxxx.
