### ISSUE TITLE
Name non-constant identifiers using lowerCamelCase.

### ISSUE THREAD

**Issue by jaggerwang** [spkersten/dart_functional_data#7]
There is a naming warning for the generated code in VSCode. It's not affect function, but annoying. 
![image](https://user-images.githubusercontent.com/1255011/63001389-1eaccb00-bea6-11e9-8dc7-a84f687b7bd9.png)

**Comment by modulovalue** [comment]
These rules are also being violated:
// ignore_for_file: annotate_overrides, join_return_with_assignment, type_annotate_public_apis

[a solution would be to add an ignore_for_file line to generated files](https://github.com/google/built_value.dart/blob/91dd5afd2263b6eb5d25551bcbbd6e88d6bb36b3/example/lib/collections.g.dart#L420).

**Comment by spkersten** [comment]
We exclude `*.g.dart` files from analysis, which could be a quick mitigation. When I've time, I'll generate better names and add the warning suppressions.

**Comment by spkersten** [comment]
The code is now generated with ignore_for_file for these warnings.
