### ISSUE TITLE
Could the generated class keep private with the original class?

### ISSUE THREAD

**Issue by jaggerwang** [spkersten/dart_functional_data#9]
The original class `_ViewModel` is private, but the generated class is `$_ViewModel`, which is not private. It lead to name conflict when export multiple modules that have the same class `_ViewModel`, but this should be ok.

**Comment by spkersten** [comment]
Probably all generated `$Foo` classes should be private as they are only supposed to be used by `Foo`.

**Comment by spkersten** [comment]
This change would be backwards-incompatible.

**Comment by spkersten** [comment]
All generated symbols are now private.
